#!/bin/bash
# scripts/package: build and tgz all supported platforms and architectures
BIN=p-diag-collectorDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
$DIR/clean
VERSION=$(git describe --abbrev=0 --tags)
ORIG=$(git branch --show-current)
echo "packaging $VERSION$"
git checkout $VERSION
GOOS=darwin GOARCH=amd64 go build -o bin/$BIN .
tar czvf ./bin/$BIN-$VERSION-darwin-amd64.tgz ./bin/$BIN
GOOS=darwin GOARCH=arm64 go build -o bin/$BIN .
tar czvf ./bin/$BIN-$VERSION-darwin-arm64.tgz ./bin/$BIN
GOOS=linux GOARCH=amd64 go build -o bin/$BIN .
tar czvf ./bin/$BIN-$VERSION-linux-amd64.tgz ./bin/$BIN
GOOS=linux GOARCH=arm64 go build -o bin/$BIN .
tar czvf ./bin/$BIN-$VERSION-linux-arm64.tgz ./bin/$BIN
git checkout $ORIG
