#!/bin/bash
# scripts/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
$DIR/bootstrap && \
go mod verify
